[package]
name = "JOT-Container"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.92"
jot-proto = "1.0.0"
lazy_static = "1.5.0"
prost = "0.14.4"
tokio = { version = "1", features = ["macros", "process", "rt-multi-thread", "signal", "time"] }
tokio-stream = "0.1.19"
tonic = "0.14.6"
tonic-health = "0.14.6"
tonic-prost = "0.14.6"
wasmtime = "49.0.1"
wasmtime-wasi = { version = "49.0.1", features = ["p1"] }
